import java.sql.Date;

/**
 * Container.java
 *
 * This class contains information about packages that media come in.
 * It normally corresponds to a single UPC-coded retail item
 * Could refer to a single movie, but can also be a compilation that comes as a set
 *
 * In the case of digital files, this will be the file container (MP4, MKV) itself
 * In case of VOD services, this will be the name of the entry in the library
 */
class Container {
    int containerID = -1; //autogenerated by DB
    String name;
    long barcode; //UPC-A, or EAN-13
    int locationID = -1;
    Date purchaseDate = new Date(0);
    int borrowerID = -1;
    boolean sell;
    boolean sold;

    //Construct with just name. Other fields are optional, use setters
    Container(String name) {
        this.name = name;
    }



}
